### ISSUE TITLE
How to use non midi instrument?

### ISSUE THREAD

**Issue by billchenxi** [icoxfog417/magenta_session#4]
Hi there,
is there a way I can use non-midi instrument? Also do you mind to tell us how to setup? From your instruction it seems very simple, but I am still confuse what kind of of brand I need purchase and etc.
Sorry to bother you and thanks a lot,
Bill

**Comment by icoxfog417** [comment]
Thank you for asking! 
`magenta_session` use [`Web MIDI API`](https://www.w3.org/TR/webmidi/) to support the instrument. And the name `Web *MIDI* API` means only the instruments that support MIDI output could be used.

Any instruments that have `USB MIDI` feature can connect. For example, KORG microKET/nanoKEY, Roland A-800PRO and so on.
